import { Roboto } from "next/font/google";
import "./globals.css";
import { ReactQueryClientProvider } from "./context/ReactQueryClientProvider";
import { AuthProvider } from "./context/AuthProvider";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Restaurants Map Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ReactQueryClientProvider>
          <AuthProvider>
            {children}
            <footer>Footer</footer>
          </AuthProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
